/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ItemDAO;
import DAO.SuplierDAO;
import DTO.Item;
import DTO.SupRolde;
import DTO.Supplier;
import java.sql.Connection;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class MainManagementItem extends javax.swing.JFrame {

    /**
     * Creates new form MainManagementItem
     */
    public static Connection cn;
    DefaultTableModel tableSup, tableItem;
    public static String id_item, id_suplier;
    ItemDAO itemDAO = new ItemDAO();
    public static boolean addNew = false;
    SuplierDAO supDAO = new SuplierDAO();

    public MainManagementItem() {
        initComponents();
        loadSup();
        loadItem();
        loadSupRole();
        setLocationRelativeTo(null);
    }

    public void loadSup() {
        cn = myLibrary.myConnection.makeConnection();
        try {
            if (cn != null) {
                Vector data = new Vector();
                Vector header = new Vector();
                Vector<Supplier> tmp = SuplierDAO.getAccounts();
                for (Supplier a : tmp) {
                    Vector row = new Vector();
                    row.add(a.getSupCode());
                    row.add(a.getSupName());
                    row.add(a.getAddress());
                    row.add(a.isCollaborating());
                    data.add(row);
                }
                header.add("Supplier Code");
                header.add("Supplier Name");
                header.add("Address");
                header.add("Collaborating");

                tableSup = (DefaultTableModel) tblSup.getModel();
                tableSup.setDataVector(data, header);
            }
        } catch (Exception e) {
            if (cn == null) {
                JOptionPane.showMessageDialog(jMenu1, "Sql Server dont connected!");
            }
            e.printStackTrace();
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                }
            } catch (Exception e) {
                if (cn == null) {
                    JOptionPane.showMessageDialog(jMenu1, "Sql Server dont connected!");
                }
                e.printStackTrace();
            }
        }
    }

    public void loadSupRole() {
        Vector<SupRolde> result = SuplierDAO.getRole();
        if (result != null && result.size() > 0) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cbxSup.getModel();
            model.removeAllElements();
            model.addElement("");
            for (SupRolde r : result) {
                model.addElement(r.getSupCode() + "-" + r.getSupName());
            }
        }
    }

    public void loadItem() {
        cn = myLibrary.myConnection.makeConnection();
        try {
            if (cn != null) {
                Vector data = new Vector();
                Vector header = new Vector();
                Vector<Item> tmp = ItemDAO.getAllItems();
                for (Item a : tmp) {
                    Vector row = new Vector();
                    row.add(a.getItemCode());
                    row.add(a.getItemName());
                    row.add(a.getSupCode());
                    row.add(a.getUnit());
                    row.add(a.getPrice());
                    row.add(a.isSupplying());
                    data.add(row);
                }

                header.add("Item Code");
                header.add("Item Name");
                header.add("Suplier");
                header.add("Unit");
                header.add("Price");
                header.add("Supply");

                tableItem = (DefaultTableModel) tblItem.getModel();
                tableItem.setDataVector(data, header);
            }
        } catch (Exception e) {
            if (cn == null) {
                JOptionPane.showMessageDialog(jMenu1, "Sql Server dont connected!");
            }
            e.printStackTrace();
        } finally {
            try {
                if (cn != null) {
                    cn.close();
                }
            } catch (Exception e) {
                if (cn == null) {
                    JOptionPane.showMessageDialog(jMenu1, "Sql Server dont connected!");
                }
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSup = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodeSup = new javax.swing.JTextField();
        txtNameSup = new javax.swing.JTextField();
        txtAddressSup = new javax.swing.JTextField();
        cbxCollaborating = new javax.swing.JCheckBox();
        btnNewSup = new javax.swing.JButton();
        btnSaveSup = new javax.swing.JButton();
        btnDelSup = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodeItem = new javax.swing.JTextField();
        txtPriceItem = new javax.swing.JTextField();
        txtUnitItem = new javax.swing.JTextField();
        txtNameItem = new javax.swing.JTextField();
        cbxSup = new javax.swing.JComboBox<>();
        cbxSupItem = new javax.swing.JCheckBox();
        btnNewItem = new javax.swing.JButton();
        bntSaveItem = new javax.swing.JButton();
        btnDelItem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cbLogOut = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Management");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSup);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("do ngoc phuc"));

        jLabel1.setText("Code:");

        jLabel2.setText("Name:");

        jLabel3.setText("Address:");

        jLabel4.setText("Collaborating:");

        btnNewSup.setText("Add New");
        btnNewSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSupActionPerformed(evt);
            }
        });

        btnSaveSup.setText("Save");
        btnSaveSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSupActionPerformed(evt);
            }
        });

        btnDelSup.setText("Delete");
        btnDelSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxCollaborating)
                            .addComponent(txtNameSup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddressSup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnNewSup)
                        .addGap(50, 50, 50)
                        .addComponent(btnSaveSup)
                        .addGap(52, 52, 52)
                        .addComponent(btnDelSup)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNameSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddressSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxCollaborating))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewSup)
                    .addComponent(btnSaveSup)
                    .addComponent(btnDelSup))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Suplier", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Suplier", "Unit", "Price", "Suply"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItem);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 214, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("New Code:");

        jLabel6.setText("New Name;");

        jLabel7.setText("Supplier:");

        jLabel8.setText("Unit:");

        jLabel9.setText("Price:");

        jLabel10.setText("Supplying:");

        cbxSup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNewItem.setText("Add New");
        btnNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewItemActionPerformed(evt);
            }
        });

        bntSaveItem.setText("Save");
        bntSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveItemActionPerformed(evt);
            }
        });

        btnDelItem.setText("Delete");
        btnDelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSupItem)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPriceItem, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(txtNameItem, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(txtUnitItem, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(txtCodeItem)
                                .addComponent(cbxSup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnNewItem)
                        .addGap(55, 55, 55)
                        .addComponent(bntSaveItem)
                        .addGap(69, 69, 69)
                        .addComponent(btnDelItem)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUnitItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPriceItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbxSupItem))
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewItem)
                    .addComponent(bntSaveItem)
                    .addComponent(btnDelItem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1162, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Item", jPanel2);

        jMenu1.setText("File");

        cbLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cbLogOut.setSelected(true);
        cbLogOut.setText("LOG OUT");
        cbLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(cbLogOut);

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("jMenuItem1");
        jMenu2.add(jMenuItem1);

        jMenu4.setText("jMenu4");
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLogOutActionPerformed
        // TODO add your handling code here:
        int anwser = JOptionPane.showConfirmDialog(jMenu1, "Do you want to log out?");
        if (anwser == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login lg = new Login();
            lg.setVisible(true);
            JOptionPane.showMessageDialog(lg, "Log out is succesful");
        }
    }//GEN-LAST:event_cbLogOutActionPerformed

    private void setModelSup(Supplier sp) {
        txtCodeSup.setText(String.valueOf(sp.getSupCode()));
        txtNameSup.setText(String.valueOf(sp.getSupName()));
        txtAddressSup.setText(String.valueOf(sp.getAddress()));
        txtCodeSup.setEditable(false);
        cbxCollaborating.setSelected(sp.isCollaborating());
        int index = tblSup.getSelectedRow();

        if (("" + tblSup.getValueAt(index, 4)).equals("true")) {
            cbxCollaborating.setSelected(true);
        }
    }

    private void tblSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupMouseClicked
        // TODO add your handling code here:
        int id = tblSup.rowAtPoint(evt.getPoint());
        id_suplier = tblSup.getValueAt(id, 0).toString();
        Supplier sp = supDAO.getSupByID(id_suplier);
        tblSup.setEditingColumn(id);
        setModelSup(sp);

    }//GEN-LAST:event_tblSupMouseClicked

    private void setModelItem(Item ee) {
        txtCodeItem.setText(String.valueOf(ee.getItemCode()));
        txtNameItem.setText(String.valueOf(ee.getItemName()));
        int index = tblItem.getSelectedRow();
        if (("" + tblItem.getValueAt(index, 3)).equals(ee.getSupCode())) {
            cbxSup.setSelectedItem(ee.getSupCode());
        }
        txtUnitItem.setText(String.valueOf(ee.getUnit()));
        txtPriceItem.setText(String.valueOf(ee.getPrice()));
        if (("" + tblItem.getValueAt(index, 6)).equals("true")) {
            cbxSupItem.setSelected(true);
        }

    }
    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        // TODO add your handling code here:
        int idItem = tblItem.rowAtPoint(evt.getPoint());
        id_item = tblItem.getValueAt(idItem, 0).toString();
        Item it = itemDAO.getItemByID(id_item);
        tblItem.setEditingColumn(idItem);
        setModelItem(it);
    }//GEN-LAST:event_tblItemMouseClicked

    private void resetSup() {
        txtCodeSup.setText("");
        txtNameSup.setText("");
        txtAddressSup.setText("");
        cbxCollaborating.setSelected(false);
        txtCodeSup.requestFocus();
        txtCodeSup.setEditable(true);
    }

    private void btnNewSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSupActionPerformed
        // TODO add your handling code here:
        resetSup();
    }//GEN-LAST:event_btnNewSupActionPerformed

    private boolean checkValid() {
        String s = "";

        return true;
    }

    private Supplier getModelSup() {
        Supplier sp = new Supplier();
        sp.setSupCode(txtCodeSup.getText());
        sp.setSupName(txtNameSup.getText());
        sp.setAddress(txtAddressSup.getText());
        boolean collaborating = false;
        if (cbxCollaborating.isSelected()) {
            collaborating = true;
        } else {
            collaborating = false;
        }
        sp.setCollaborating(collaborating);
        return sp;
    }

    private void btnSaveSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSupActionPerformed
        // TODO add your handling code here:
        Supplier sp = getModelSup();
        int anwser = JOptionPane.showConfirmDialog(jMenu1, "Do you want to add(YES) or update(NO) suplier?", "Question", JOptionPane.YES_NO_OPTION);
        if (anwser == JOptionPane.YES_OPTION) {
            try {
                if (supDAO.insertSuplier(sp) > 0) {
                    JOptionPane.showMessageDialog(this, "Add Successful!");
                    loadSup();
                } else {
                    JOptionPane.showMessageDialog(jMenu1, "Dont add new suplier!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.toString());
            }
        }
        if (anwser == JOptionPane.NO_OPTION) {
            try {
                if (supDAO.updateSuplier(sp) > 0) {
                    JOptionPane.showMessageDialog(this, "Update Successful!");
                    loadSup();
                } else {
                    JOptionPane.showMessageDialog(jMenu1, "Dont update this suplier!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.toString());
            }
        }
//        if (btnNewSup.isSelected() && addNew == true) {
//
//            try {
//                if (supDAO.insertSuplier(sp) > 0) {
//                    JOptionPane.showMessageDialog(this, "Add Successful!");
//                    loadSup();
//                } else {
//                    JOptionPane.showMessageDialog(jMenu1, "Dont add new suplier!");
//                }
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Error: " + e.toString());
//            }
//        }
//        if (tableSup.getDataVector() != null) {
//            try {
//                if (supDAO.updateSuplier(sp) > 0) {
//                    JOptionPane.showMessageDialog(this, "Update Successful!");
//                    loadSup();
//                } else {
//                    JOptionPane.showMessageDialog(jMenu1, "Dont update this suplier!");
//                }
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Error: " + e.toString());
//            }
//        }
    }//GEN-LAST:event_btnSaveSupActionPerformed

    private void btnDelSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSupActionPerformed
        // TODO add your handling code here:
        int index = tblSup.getSelectedRow();
        if (index > 0) {
            int anwser = JOptionPane.showConfirmDialog(null, "Do you want to Delete?", "WARNING", JOptionPane.YES_NO_OPTION);

            if (anwser == JOptionPane.YES_OPTION) {
                if (index > 0) {
                    supDAO.deleteSuplier(id_suplier);
                    JOptionPane.showMessageDialog(null, "Delete was successful!");
                    loadSup();
                }
            }
        }
    }//GEN-LAST:event_btnDelSupActionPerformed

    private void resetItem() {
        txtCodeItem.setText("");
        txtCodeItem.setEditable(true);
        txtNameItem.setText("");
        txtUnitItem.setText("");
        txtPriceItem.setText("");
        cbxSup.setSelectedIndex(0);
        cbxSupItem.setSelected(false);
        requestFocus();
    }

    private void btnNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewItemActionPerformed
        // TODO add your handling code here:
        resetItem();

    }//GEN-LAST:event_btnNewItemActionPerformed

    public Item getmodelItem() {
        Item it = new Item();
        it.setItemCode(txtCodeItem.getText());
        it.setItemName(txtNameItem.getText());
        it.setPrice(Double.parseDouble(txtPriceItem.getText()));
        it.setUnit(txtUnitItem.getText());
        String tmp = "" + cbxSup.getSelectedItem();
        String supID = tmp.split("-")[0];
        it.setSupCode(supID);
        boolean isSupply = false;
        if (cbxSupItem.isSelected()) {
            isSupply = true;
        }
        it.setSupplying(isSupply);
        return it;
    }
    private void bntSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveItemActionPerformed
        // TODO add your handling code here:
        Item it = getmodelItem();
        int index = tblItem.getSelectedRow();
        int anwser = JOptionPane.showConfirmDialog(jMenu1, "Do you want to add(YES) or update(No) item?", "Question?", JOptionPane.YES_NO_OPTION);
        if (anwser == JOptionPane.YES_OPTION) {
            try {
                if (itemDAO.insertItem(it) > 0) {
                    JOptionPane.showMessageDialog(jMenu1, "Add Successful!");
                    loadItem();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(jMenu1, "Dont add successful!");
            }
        }
        if (anwser == JOptionPane.NO_OPTION) {
            try {
                if (itemDAO.updateItem(it) > 0) {
                    JOptionPane.showMessageDialog(jMenu1, "Update item Successful!");
                    loadItem();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(jMenu1, "Dont update item successful!");
            }
        }
    }//GEN-LAST:event_bntSaveItemActionPerformed

    private void btnDelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelItemActionPerformed
        // TODO add your handling code here:
        int index = tblItem.getSelectedRow();
        if (index > 0) {
            int anwser = JOptionPane.showConfirmDialog(jMenu1, "Do you want to Delete?", "WARNING", JOptionPane.YES_NO_OPTION);

            if (anwser == JOptionPane.YES_OPTION) {
                if (index > 0) {
                    itemDAO.deleteItem(id_item);
                    JOptionPane.showMessageDialog(jMenu1, "Delete was successful!");
                    loadSup();
                }
            }
        }
    }//GEN-LAST:event_btnDelItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainManagementItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainManagementItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainManagementItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainManagementItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainManagementItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSaveItem;
    private javax.swing.JButton btnDelItem;
    private javax.swing.JButton btnDelSup;
    private javax.swing.JButton btnNewItem;
    private javax.swing.JButton btnNewSup;
    private javax.swing.JButton btnSaveSup;
    private javax.swing.JCheckBoxMenuItem cbLogOut;
    private javax.swing.JCheckBox cbxCollaborating;
    private javax.swing.JComboBox<String> cbxSup;
    private javax.swing.JCheckBox cbxSupItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblSup;
    private javax.swing.JTextField txtAddressSup;
    private javax.swing.JTextField txtCodeItem;
    private javax.swing.JTextField txtCodeSup;
    private javax.swing.JTextField txtNameItem;
    private javax.swing.JTextField txtNameSup;
    private javax.swing.JTextField txtPriceItem;
    private javax.swing.JTextField txtUnitItem;
    // End of variables declaration//GEN-END:variables
}
